-- Exact rollback for 20261224000000 (row 68): preflight 2's output, saved from production on 7 Oct 2026 before applying.
-- Run it in one transaction (begin; ... commit;) only if the revoke has to be undone.
grant MAINTAIN, REFERENCES, TRIGGER on table ai_analyses to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER on table ai_settings to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER on table audit_log to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER on table suggestions to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table analysis_rules to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table blocks to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table churn_drivers to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table client_assignments to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table client_groups to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table client_services to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table clients to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table demand_settings to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table edges to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table first_principles to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table issue_events to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table issue_links to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table issue_owners to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table issue_sources to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table issues to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table lead_sources to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table lever_settings to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table market_conditions to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table market_schedule to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table memberships to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table narrations to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table people to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table person_capacity_factors to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table person_leave to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table person_roles to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table person_skills to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table process_placements to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table process_revisions to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table processes to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table reports to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table robustness_results to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table roles to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table runs to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table scenarios to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table seasonality to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table service_servicing to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table services to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table sources to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table steps to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table workspace_access_emails to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table workspace_domains to authenticated;
grant MAINTAIN, REFERENCES, TRIGGER, TRUNCATE on table workspaces to authenticated;
